spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: mohamed
    password: mohamed
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    spring:
      devtools:
        restart:
          enabled: true
    ##################################################
#  security:
#    user:
#      name: admin
#      password: 1234
#      roles: ADMIN,USER
##############################################################

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/schools?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect



############################################################
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application-description: "API for School Management System"
application-version: "1.0.0"






